//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Sadik .
//     Runtime Version:1.3 or  _13
//       visit website :  http://guercifzone.net/
//     my github : https://github.com/sadik-fattah
//     the code  is  for  free t  change and  edit :)
// </auto-generated>
//------------------------------------------------------------------------------
namespace webcam_13
{
	using System;
	using System.Collections.Generic;
	using System.Web;
	using System.Data.Linq;
	using System.Web.UI;
	using System.Web.UI.WebControls;
	using System.IO;
	using System.Web.Services;

	public partial class Default : System.Web.UI.Page
	{
		
		public void button1Clicked (object sender, EventArgs args)
		{
			if (!this.IsPostBack)
			{
				if (Request.InputStream.Length > 0)
				{
					using (StreamReader reader = new StreamReader(Request.InputStream))
					{
						string hexString = Server.UrlEncode(reader.ReadToEnd());
						string imageName = DateTime.Now.ToString("dd-MM-yy hh-mm-ss");
						string imagePath = string.Format("~/Captures/{0}.png", imageName);
						File.WriteAllBytes(Server.MapPath(imagePath), ConvertHexToBytes(hexString));
						Session["CapturedImage"] = ResolveUrl(imagePath);
					}
				}
			}
		}
		private static byte[] ConvertHexToBytes(string hex)
		{
			byte[] bytes = new byte[hex.Length / 2];
			for (int i = 0; i < hex.Length; i += 2)
			{
				bytes[i / 2] = Convert.ToByte(hex.Substring(i, 2), 16);
			}
			return bytes;
		}

		[WebMethod(EnableSession = true)]
		public static string GetCapturedImage()
		{
			string url = HttpContext.Current.Session["CapturedImage"].ToString();
			HttpContext.Current.Session["CapturedImage"] = null;
			return url;
		}
	
	}
}

