//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Sadik .
//     Runtime Version:1.3 or  _13
//       visit website :  http://guercifzone.net/
//     my github : https://github.com/sadik-fattah
//     the code  is  for  free t  change and  edit :)
// </auto-generated>
//------------------------------------------------------------------------------
namespace webcam_13
{
	using System;
	using System.Web;
	using System.Web.UI;

	public partial class Default
	{
		//protected System.Web.UI.WebControls.from ;
		protected System.Web.UI.WebControls.Image imgCapture;
			protected System.Web.UI.WebControls.Button btnCapture;
	}
}

